# Generated by Django 3.0.6 on 2020-06-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pianos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='', max_length=254)),
                ('price', models.DecimalField(decimal_places=0, max_digits=5)),
                ('age', models.DecimalField(decimal_places=0, max_digits=3)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
